name: Daily Python Script

on:
  schedule:
    # Runs every day at 5:00 PM IST (11:30 AM UTC)
    - cron: "30 11 * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Show repo files
        run: pwd && ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run copy.py
        run: python copy.py

      - name: Run GenerateReport.py
        run: python GenerateReport.py
      
     
