name: Daily Python Script

on:
  schedule:
    # Runs every day at 9:00 AM UTC
    - cron: "30 11 * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python copy.py
        name: Run script
        run: python GenerateReport.py